<?php $this->headScript()->appendFile($this->basePath() . '/js/jquery-ui.min.js', 'text/javascript'); ?>
<?php if (!$this->cards()->getPlayer()): ?>
    <div class="alert alert-info clearfix">
        <strong>Hey lurker!</strong> You are currently just spectating. Sign in above to join the fun!
    </div>
<?php elseif (!$this->cards()->isInGame($game)): ?>
    <div class="alert alert-info clearfix">
        <strong>Hey <?php echo $this->cards()->getPlayer()->displayName; ?>!</strong> You haven't joined this game yet!
        <a class="btn btn-inverse" href="<?php echo $this->url('games/game/join', array('game_id' => $game->id)); ?>">Join Game</a>
    </div>
<?php endif; ?>

<div class="row-fluid">
    <div class="span10">

        <div class="row-fluid">

            <h1><?php echo $game->name; ?></h1>

            <div class="span3">
                <div class="card card-black">
                    <?php echo $blackCard->text; ?>
                </div>
            </div>

            <div class="span7">
                <div class="row-fluid">
                    <div class="span7">
                    <?php for($i=0; $i<$blackCard->blankCount; $i++): ?>
                        <div class="cards card card-small pull-left ui-state-disabled">
                        </div>
                    <?php endfor; ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span7">
                        <a href="#" class="btn btn-large btn-inverse">Submit Answer</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="span2">
        <?php if (count($game->players) > 0): ?>
            <table class="table table-striped player-list">
                <thead>
                    <tr>
                        <th>Player</th>
                        <th class="points-column">Points</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($game->players as $player): ?>
                    <tr>
                        <td>
                            <?php echo $this->gravatar($player->emailHash, array('img_size' => 20)); ?>
                            <?php echo $player->displayName; ?>
                        </td>
                        <td><?php echo $player->points; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
                No players in this game.
        <?php endif; ?>
    </div>
</div>

<div class="row-fluid">
    <?php if ($this->cards()->isInGame($game)): ?>
        <h3>Your Cards</h3>

        <div class="span12 cards">
            <?php foreach ($cards as $card): ?>
                <div class="card card-small pull-left">
                <?php echo  $card->text; ?>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

<script>
$(function() {
    $( "div.cards" ).sortable({
        connectWith: 'div.cards',
        items: "div:not(.ui-state-disabled)"
    }).disableSelection();
});
</script>
