<?php if (!$this->cards()->getPlayer()): ?>
    <div class="alert alert-info clearfix">
        <strong>Hey lurker!</strong> You are currently just spectating. Sign in above to join the fun!
    </div>
<?php else: ?>
    <?php if (!$this->cards()->isInGame($game)): ?>
        <div class="alert alert-info clearfix">
            <strong>Hey <?php echo $this->cards()->getPlayer()->displayName; ?>!</strong> You haven't joined this game yet!
            <a class="btn btn-inverse" href="<?php echo $this->url('games/game/join', array('game_id' => $game->id)); ?>">Join Game</a>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if ($newRound): ?>
    <meta http-equiv="refresh" content="4; url=<?php echo $this->url('games/game', array(), true); ?>">
    <div class="alert alert-success clearfix">
        <strong>A new round is starting!</strong> You'll be redirected.
    </div>
<?php else: ?>
    <div class="alert alert-info clearfix">
        <strong>Sit tight!</strong> The next round will begin shortly.
    </div>
<?php endif; ?>

<div class="row-fluid">
    <div class="span2">
        <div class="card card-black">
            <?php echo $blackCard->text; ?>
        </div>
    </div>
    <div class="span10">
        <?php foreach ($players as $player): ?>
        <div class="row">

            <div class="span<?php echo count($player->cards) + 1;?>">
                <?php foreach ($player->cards as $card): ?>
                    <div class="card card-small pull-left">
                    <?php echo $card->text; ?>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="span1">
                <?php echo $this->gravatar($player->emailHash); ?><br/>
                <?php echo $player->displayName; ?>
            </div>

        </div>
        <?php endforeach; ?>
    </div>
</div>
<script>
<?php if (!$newRound): ?>
setTimeout(function() { $('#content').load('<?php echo $this->url('games/game/round', array(), true); ?>?ajax=true'); }, 1500);
<?php else: ?>
setTimeout(function() { window.location = '<?php echo $this->url('games/game', array(), true); ?>'; }, 1500);
<?php endif; ?>
</script>
