<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Cards Against Humanity')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/cah-game.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">Cards Against Humanity</a>
                    <div class="nav-collapse collapse">
                        <?php echo $this->navigation('navigation')->menu()->setPartial(array('edp-cards-client/topnav.phtml', 'default')); ?>
                        <?php if (!$this->cards()->getPlayer()): ?>
                            <?php $loginForm->prepare()->setAttributes(array('action' => $this->url('login'), 'class' => 'navbar-form pull-right')); ?>
                            <?php echo $this->form()->openTag($loginForm); ?>
                                <?php echo $this->formInput($loginForm->get('email')->setAttribute('class', 'span2')); ?>
                                <?php echo $this->formInput($loginForm->get('displayName')->setAttribute('class', 'span2')); ?>
                                <input type="hidden" name="backurl" value="<?php echo $this->url(null, array(), array(), true); ?>">
                                <?php echo $this->formButton($loginForm->get('submit')->setAttribute('class', 'btn')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        <?php else: ?>
                            <div class="pull-right logged-in">
                                <?php echo $this->gravatar($this->cards()->getPlayer()->emailHash, array('img_size' => 30)); ?>
                                <?php echo $this->cards()->getPlayer()->displayName; ?>
                                <a href="<?php echo $this->url('logout'); ?>">[Logout]</a>
                            </div>

                        <?php endif; ?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Evan Coury.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
